apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ewogICJhdXRocyIgOiB7CiAgICAiaHR0cHM6Ly9pbmRleC5kb2NrZXIuaW8vdjEvIiA6IHsKCiAgICB9LAogICAgImdoY3IuaW8iIDogewogICAgICAiYXV0aCI6ICJTV3g1WVV4cGRtbHVaM04wYjI1bE9tZG9jRjlVZEVkS2FrRnFha0pwVlVoU2FHb3dVMngyZVc5MlZWZHhTMlJrZEdneFlsUkJWRlk9IgogICAgfQogIH0sCiAgImNyZWRzU3RvcmUiIDogImRlc2t0b3AiLAogICJzdGFja09yY2hlc3RyYXRvciIgOiAic3dhcm0iLAogICJleHBlcmltZW50YWwiIDogImRpc2FibGVkIgp9Cg==
type: kubernetes.io/dockerconfigjson
